### PR TITLE
Added a missing devDependency

### PR DESCRIPTION
**Pull request by ironicnet**
Forked the master branch, did a "npm install" and then tried to run the "gulp build" command.

The "through2" was not found, so i added it to the dev dependencies...

### CODE REVIEW

**Comment by mvvsubbu** [comment]
Looks fine.. Please merge with master and update the PR

**Comment by ironicnet** [comment]
Fork merged from master. It should be good to go.

Thanks!

**Comment by mvvsubbu** [comment]
Another PR went in and again merge is blocked. Can you do it again.

**Comment by ironicnet** [comment]
Ok, Let's try again :P

**Comment by mvvsubbu** [comment]
Again blocked.. I am doing this time thanks for reporting.

**Pull request closed without merging**
